/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 36
#line 1 "lfi-amd64.leg"

#include <stdio.h>
#include <util.h>
#include <assert.h>

#include "amd64.h"
#include "ht.h"
#include "op.h"

extern FILE* input;
extern FILE* output;

typedef struct transform {
    char* val;
    char* guard;
    char* post;
} Transform;

static void
tfree(Transform t)
{
    free(t.val);
    free(t.guard);
    free(t.post);
}

#define YYSTYPE Transform

#define YY_INPUT(buf, result, max_size)      \
{                                            \
    result = fread(buf, 1, max_size, input); \
}                                            \

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_RC(yycontext *yy); /* 36 */
YY_RULE(int) yy_LC(yycontext *yy); /* 35 */
YY_RULE(int) yy_RB(yycontext *yy); /* 34 */
YY_RULE(int) yy_LB(yycontext *yy); /* 33 */
YY_RULE(int) yy_EXCLAM(yycontext *yy); /* 32 */
YY_RULE(int) yy_RELOC(yycontext *yy); /* 31 */
YY_RULE(int) yy_IMM_RAW(yycontext *yy); /* 30 */
YY_RULE(int) yy_ID(yycontext *yy); /* 29 */
YY_RULE(int) yy_XREG(yycontext *yy); /* 28 */
YY_RULE(int) yy_JUMP(yycontext *yy); /* 27 */
YY_RULE(int) yy_MOV(yycontext *yy); /* 26 */
YY_RULE(int) yy_BALANCED_RAW(yycontext *yy); /* 25 */
YY_RULE(int) yy_BALANCED(yycontext *yy); /* 24 */
YY_RULE(int) yy_IMM(yycontext *yy); /* 23 */
YY_RULE(int) yy_RP(yycontext *yy); /* 22 */
YY_RULE(int) yy_XREG_NOSP(yycontext *yy); /* 21 */
YY_RULE(int) yy_LP(yycontext *yy); /* 20 */
YY_RULE(int) yy_Addr(yycontext *yy); /* 19 */
YY_RULE(int) yy_NAME(yycontext *yy); /* 18 */
YY_RULE(int) yy__(yycontext *yy); /* 17 */
YY_RULE(int) yy_REG(yycontext *yy); /* 16 */
YY_RULE(int) yy_COMMA(yycontext *yy); /* 15 */
YY_RULE(int) yy_AddrNoMod(yycontext *yy); /* 14 */
YY_RULE(int) yy_LEA(yycontext *yy); /* 13 */
YY_RULE(int) yy_EOL(yycontext *yy); /* 12 */
YY_RULE(int) yy_Any(yycontext *yy); /* 11 */
YY_RULE(int) yy_COMMENT(yycontext *yy); /* 10 */
YY_RULE(int) yy_Syscall(yycontext *yy); /* 9 */
YY_RULE(int) yy_Branch(yycontext *yy); /* 8 */
YY_RULE(int) yy_Load(yycontext *yy); /* 7 */
YY_RULE(int) yy_Store(yycontext *yy); /* 6 */
YY_RULE(int) yy_Lea(yycontext *yy); /* 5 */
YY_RULE(int) yy_Directive(yycontext *yy); /* 4 */
YY_RULE(int) yy_Label(yycontext *yy); /* 3 */
YY_RULE(int) yy_INDENT(yycontext *yy); /* 2 */
YY_RULE(int) yy_Insn(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_XREG(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_XREG\n"));
  {
#line 244
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_REG(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_REG\n"));
  {
#line 225
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_XREG_NOSP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_XREG_NOSP\n"));
  {
#line 190
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IMM(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IMM\n"));
  {
#line 159
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NAME(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NAME\n"));
  {
#line 155
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Directive(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Directive\n"));
  {
#line 151
  
    mkdirective(xasprintf("%s\n", yytext));
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Label(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Label\n"));
  {
#line 147
  
    mklabel(strndup(yytext, yyleng));
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Any(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Any\n"));
  {
#line 142
  
    if (yyleng > 0)
        mkinsn("%s\n", yytext);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Syscall(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Syscall\n"));
  {
#line 134
  
    mkinsn("call *%%gs:0x0\n")
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_JUMP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_JUMP\n"));
  {
#line 130
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Branch(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define j yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Branch\n"));
  {
#line 125
  
    mkinsn("%s *%%gs:(%s)\n", j.val, lo(r.val));
    tfree(j); tfree(r);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef j
}
YY_ACTION(void) yy_1_MOV(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_MOV\n"));
  {
#line 121
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_BALANCED(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_BALANCED\n"));
  {
#line 117
  
    __ = (Transform) { .val = strndup(yytext, yyleng) }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_AddrNoMod(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define i yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_AddrNoMod\n"));
  {
#line 110
  
        __ = (Transform) {
            .val = xasprintf("%s", b.val),
        }
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef i
}
YY_ACTION(void) yy_1_AddrNoMod(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define i yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_AddrNoMod\n"));
  {
#line 104
  
        __ = (Transform) {
            .val = xasprintf("%s%s", i.val, b.val),
        }
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef i
}
YY_ACTION(void) yy_4_Addr(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define i yy->__val[-2]
#define r yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Addr\n"));
  {
#line 94
  
        __ = (Transform) {
            .guard = xasprintf("lea %s, %%r15", b.val),
            .val = xasprintf("%%gs:(%%r15d)"),
        }
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef i
#undef r
}
YY_ACTION(void) yy_3_Addr(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define i yy->__val[-2]
#define r yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Addr\n"));
  {
#line 87
  
        __ = (Transform) {
            .guard = xasprintf("lea %s%s, %%r15", i.val, b.val),
            .val = xasprintf("%%gs:(%%r15d)"),
        }
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef i
#undef r
}
YY_ACTION(void) yy_2_Addr(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define i yy->__val[-2]
#define r yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Addr\n"));
  {
#line 81
  
        __ = (Transform) {
            .val = xasprintf("%%gs:%s(%s)", i.val, lo(r.val)),
        }
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef i
#undef r
}
YY_ACTION(void) yy_1_Addr(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define i yy->__val[-2]
#define r yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Addr\n"));
  {
#line 75
  
        __ = (Transform) {
            .val = xasprintf("%%gs:(%s)", lo(r.val)),
        }
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef i
#undef r
}
YY_ACTION(void) yy_1_Store(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define r yy->__val[-2]
#define m yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Store\n"));
  {
#line 67
  
    if (a.guard)
        mkinsn("%s\n", a.guard);
    mkinsn("%s %s, %s\n", m.val, r.val, a.val);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
#undef r
#undef m
}
YY_ACTION(void) yy_1_Load(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define a yy->__val[-2]
#define m yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Load\n"));
  {
#line 61
  
    if (a.guard)
        mkinsn("%s\n", a.guard);
    mkinsn("%s %s, %s\n", m.val, a.val, r.val);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef a
#undef m
}
YY_ACTION(void) yy_1_LEA(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LEA\n"));
  {
#line 59
   __ = (Transform) { .val = strndup(yytext, yyleng) } ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Lea(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define a yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Lea\n"));
  {
#line 55
  
    mkinsn("%s %s, %s\n", l.val, a.val, r.val);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef a
#undef l
}
YY_ACTION(void) yy_1_INDENT(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_INDENT\n"));
  {
#line 48
  
    // if (yyleng > 0)
        // printf("%s", yytext);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_RC(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RC"));  if (!yymatchChar(yy, '}')) goto l1;  if (!yy__(yy)) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "RC", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RC", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LC(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LC"));  if (!yymatchChar(yy, '{')) goto l2;  if (!yy__(yy)) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "LC", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LC", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RB(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RB"));  if (!yymatchChar(yy, ']')) goto l3;  if (!yy__(yy)) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "RB", yy->__buf+yy->__pos));
  return 1;
  l3:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RB", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LB(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LB"));  if (!yymatchChar(yy, '[')) goto l4;  if (!yy__(yy)) goto l4;
  yyprintf((stderr, "  ok   %s @ %s\n", "LB", yy->__buf+yy->__pos));
  return 1;
  l4:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LB", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EXCLAM(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EXCLAM"));  if (!yymatchChar(yy, '!')) goto l5;  if (!yy__(yy)) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "EXCLAM", yy->__buf+yy->__pos));
  return 1;
  l5:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EXCLAM", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RELOC(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RELOC"));  if (!yymatchChar(yy, ':')) goto l6;  if (!yy_ID(yy)) goto l6;  if (!yymatchChar(yy, ':')) goto l6;  if (!yy_ID(yy)) goto l6;
  yyprintf((stderr, "  ok   %s @ %s\n", "RELOC", yy->__buf+yy->__pos));
  return 1;
  l6:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RELOC", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IMM_RAW(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IMM_RAW"));
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;  if (!yymatchChar(yy, '$')) goto l8;  if (!yy__(yy)) goto l8;  goto l9;
  l8:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;
  }
  l9:;	
  {  int yypos10= yy->__pos, yythunkpos10= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;
  l12:;	
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l13;  goto l12;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }  goto l10;
  l11:;	  yy->__pos= yypos10; yy->__thunkpos= yythunkpos10;  if (!yy_BALANCED_RAW(yy)) goto l14;  goto l10;
  l14:;	  yy->__pos= yypos10; yy->__thunkpos= yythunkpos10;  if (!yy_RELOC(yy)) goto l7;
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IMM_RAW", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IMM_RAW", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ID(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ID"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\100\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l15;
  l16:;	
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\150\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l17;  goto l16;
  l17:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ID", yy->__buf+yy->__pos));
  return 1;
  l15:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ID", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_XREG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "XREG"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l18;
#undef yytext
#undef yyleng
  }
  {  int yypos19= yy->__pos, yythunkpos19= yy->__thunkpos;  if (!yymatchString(yy, "%rax")) goto l20;  goto l19;
  l20:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%rcx")) goto l21;  goto l19;
  l21:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%rdx")) goto l22;  goto l19;
  l22:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%rbx")) goto l23;  goto l19;
  l23:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%rsi")) goto l24;  goto l19;
  l24:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%rdi")) goto l25;  goto l19;
  l25:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%rsp")) goto l26;  goto l19;
  l26:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%rbp")) goto l27;  goto l19;
  l27:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r8")) goto l28;  goto l19;
  l28:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r9")) goto l29;  goto l19;
  l29:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r10")) goto l30;  goto l19;
  l30:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r11")) goto l31;  goto l19;
  l31:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r12")) goto l32;  goto l19;
  l32:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r13")) goto l33;  goto l19;
  l33:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r14")) goto l34;  goto l19;
  l34:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchString(yy, "%r15")) goto l18;
  }
  l19:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l18;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l18;  yyDo(yy, yy_1_XREG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "XREG", yy->__buf+yy->__pos));
  return 1;
  l18:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "XREG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_JUMP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "JUMP"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l35;
#undef yytext
#undef yyleng
  }
  {  int yypos36= yy->__pos, yythunkpos36= yy->__thunkpos;  if (!yymatchString(yy, "jmp")) goto l37;  goto l36;
  l37:;	  yy->__pos= yypos36; yy->__thunkpos= yythunkpos36;  if (!yymatchString(yy, "call")) goto l35;
  }
  l36:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l35;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l35;  yyDo(yy, yy_1_JUMP, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "JUMP", yy->__buf+yy->__pos));
  return 1;
  l35:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "JUMP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MOV(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MOV"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l38;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, "mov")) goto l38;
  {  int yypos39= yy->__pos, yythunkpos39= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\000\020\202\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l39;  goto l40;
  l39:;	  yy->__pos= yypos39; yy->__thunkpos= yythunkpos39;
  }
  l40:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l38;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l38;  yyDo(yy, yy_1_MOV, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "MOV", yy->__buf+yy->__pos));
  return 1;
  l38:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MOV", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BALANCED_RAW(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "BALANCED_RAW"));  if (!yy_LP(yy)) goto l41;
  l42:;	
  {  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;
  {  int yypos44= yy->__pos, yythunkpos44= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\377\374\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l45;  goto l44;
  l45:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yy_BALANCED_RAW(yy)) goto l43;
  }
  l44:;	  goto l42;
  l43:;	  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;
  }  if (!yy_RP(yy)) goto l41;
  yyprintf((stderr, "  ok   %s @ %s\n", "BALANCED_RAW", yy->__buf+yy->__pos));
  return 1;
  l41:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BALANCED_RAW", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BALANCED(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "BALANCED"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l46;
#undef yytext
#undef yyleng
  }  if (!yy_BALANCED_RAW(yy)) goto l46;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l46;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_BALANCED, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "BALANCED", yy->__buf+yy->__pos));
  return 1;
  l46:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BALANCED", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IMM(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IMM"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l47;
#undef yytext
#undef yyleng
  }  if (!yy_IMM_RAW(yy)) goto l47;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l47;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l47;  yyDo(yy, yy_1_IMM, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "IMM", yy->__buf+yy->__pos));
  return 1;
  l47:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IMM", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RP"));  if (!yymatchChar(yy, ')')) goto l48;  if (!yy__(yy)) goto l48;
  yyprintf((stderr, "  ok   %s @ %s\n", "RP", yy->__buf+yy->__pos));
  return 1;
  l48:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_XREG_NOSP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "XREG_NOSP"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l49;
#undef yytext
#undef yyleng
  }
  {  int yypos50= yy->__pos, yythunkpos50= yy->__thunkpos;  if (!yymatchString(yy, "%rax")) goto l51;  goto l50;
  l51:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%rcx")) goto l52;  goto l50;
  l52:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%rdx")) goto l53;  goto l50;
  l53:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%rbx")) goto l54;  goto l50;
  l54:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%rsi")) goto l55;  goto l50;
  l55:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%rdi")) goto l56;  goto l50;
  l56:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%rbp")) goto l57;  goto l50;
  l57:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r8")) goto l58;  goto l50;
  l58:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r9")) goto l59;  goto l50;
  l59:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r10")) goto l60;  goto l50;
  l60:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r11")) goto l61;  goto l50;
  l61:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r12")) goto l62;  goto l50;
  l62:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r13")) goto l63;  goto l50;
  l63:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r14")) goto l64;  goto l50;
  l64:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;  if (!yymatchString(yy, "%r15")) goto l49;
  }
  l50:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l49;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l49;  yyDo(yy, yy_1_XREG_NOSP, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "XREG_NOSP", yy->__buf+yy->__pos));
  return 1;
  l49:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "XREG_NOSP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LP"));  if (!yymatchChar(yy, '(')) goto l65;  if (!yy__(yy)) goto l65;
  yyprintf((stderr, "  ok   %s @ %s\n", "LP", yy->__buf+yy->__pos));
  return 1;
  l65:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Addr(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Addr"));
  {  int yypos67= yy->__pos, yythunkpos67= yy->__thunkpos;  if (!yy_LP(yy)) goto l68;  if (!yy_XREG_NOSP(yy)) goto l68;  yyDo(yy, yySet, -3, 0);  if (!yy_RP(yy)) goto l68;  yyDo(yy, yy_1_Addr, yy->__begin, yy->__end);  goto l67;
  l68:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yy_IMM(yy)) goto l69;  yyDo(yy, yySet, -2, 0);  if (!yy_LP(yy)) goto l69;  if (!yy_XREG_NOSP(yy)) goto l69;  yyDo(yy, yySet, -3, 0);  if (!yy_RP(yy)) goto l69;  yyDo(yy, yy_2_Addr, yy->__begin, yy->__end);  goto l67;
  l69:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yy_IMM(yy)) goto l70;  yyDo(yy, yySet, -2, 0);  if (!yy_BALANCED(yy)) goto l70;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_Addr, yy->__begin, yy->__end);  goto l67;
  l70:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yy_BALANCED(yy)) goto l66;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_4_Addr, yy->__begin, yy->__end);
  }
  l67:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Addr", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l66:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Addr", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NAME(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NAME"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l71;
#undef yytext
#undef yyleng
  }  if (!yy_ID(yy)) goto l71;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l71;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l71;  yyDo(yy, yy_1_NAME, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NAME", yy->__buf+yy->__pos));
  return 1;
  l71:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NAME", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l73:;	
  {  int yypos74= yy->__pos, yythunkpos74= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos74; yy->__thunkpos= yythunkpos74;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_REG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "REG"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l75;
#undef yytext
#undef yyleng
  }
  {  int yypos76= yy->__pos, yythunkpos76= yy->__thunkpos;  if (!yymatchString(yy, "%rax")) goto l77;  goto l76;
  l77:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%rcx")) goto l78;  goto l76;
  l78:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%rdx")) goto l79;  goto l76;
  l79:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%rbx")) goto l80;  goto l76;
  l80:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%rsi")) goto l81;  goto l76;
  l81:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%rdi")) goto l82;  goto l76;
  l82:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%rsp")) goto l83;  goto l76;
  l83:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%rbp")) goto l84;  goto l76;
  l84:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r8")) goto l85;  goto l76;
  l85:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r9")) goto l86;  goto l76;
  l86:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r10")) goto l87;  goto l76;
  l87:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r11")) goto l88;  goto l76;
  l88:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r12")) goto l89;  goto l76;
  l89:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r13")) goto l90;  goto l76;
  l90:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r14")) goto l91;  goto l76;
  l91:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r15")) goto l92;  goto l76;
  l92:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%eax")) goto l93;  goto l76;
  l93:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%ecx")) goto l94;  goto l76;
  l94:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%edx")) goto l95;  goto l76;
  l95:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%ebx")) goto l96;  goto l76;
  l96:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%esi")) goto l97;  goto l76;
  l97:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%edi")) goto l98;  goto l76;
  l98:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%esp")) goto l99;  goto l76;
  l99:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%ebp")) goto l100;  goto l76;
  l100:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r8d")) goto l101;  goto l76;
  l101:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r9d")) goto l102;  goto l76;
  l102:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r10d")) goto l103;  goto l76;
  l103:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r11d")) goto l104;  goto l76;
  l104:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r12d")) goto l105;  goto l76;
  l105:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r13d")) goto l106;  goto l76;
  l106:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r14d")) goto l107;  goto l76;
  l107:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "%r15d")) goto l75;
  }
  l76:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l75;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l75;  yyDo(yy, yy_1_REG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "REG", yy->__buf+yy->__pos));
  return 1;
  l75:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "REG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_COMMA(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchChar(yy, ',')) goto l108;  if (!yy__(yy)) goto l108;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 1;
  l108:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_AddrNoMod(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "AddrNoMod"));
  {  int yypos110= yy->__pos, yythunkpos110= yy->__thunkpos;  if (!yy_IMM(yy)) goto l111;  yyDo(yy, yySet, -2, 0);  if (!yy_BALANCED(yy)) goto l111;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_AddrNoMod, yy->__begin, yy->__end);  goto l110;
  l111:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;  if (!yy_BALANCED(yy)) goto l109;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_AddrNoMod, yy->__begin, yy->__end);
  }
  l110:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "AddrNoMod", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l109:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AddrNoMod", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LEA(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LEA"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l112;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, "lea")) goto l112;
  {  int yypos113= yy->__pos, yythunkpos113= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\000\020\202\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l113;  goto l114;
  l113:;	  yy->__pos= yypos113; yy->__thunkpos= yythunkpos113;
  }
  l114:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l112;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l112;  yyDo(yy, yy_1_LEA, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "LEA", yy->__buf+yy->__pos));
  return 1;
  l112:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LEA", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos116= yy->__pos, yythunkpos116= yy->__thunkpos;  if (!yymatchChar(yy, '\n')) goto l117;  goto l116;
  l117:;	  yy->__pos= yypos116; yy->__thunkpos= yythunkpos116;  if (!yymatchString(yy, "\r\n")) goto l118;  goto l116;
  l118:;	  yy->__pos= yypos116; yy->__thunkpos= yythunkpos116;  if (!yymatchChar(yy, '\r')) goto l115;
  }
  l116:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 1;
  l115:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Any(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Any"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l119;
#undef yytext
#undef yyleng
  }
  l120:;	
  {  int yypos121= yy->__pos, yythunkpos121= yy->__thunkpos;
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;  if (!yy_EOL(yy)) goto l122;  goto l121;
  l122:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;
  }  if (!yymatchDot(yy)) goto l121;  goto l120;
  l121:;	  yy->__pos= yypos121; yy->__thunkpos= yythunkpos121;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l119;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Any, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 1;
  l119:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_COMMENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COMMENT"));  if (!yymatchString(yy, "//")) goto l123;
  l124:;	
  {  int yypos125= yy->__pos, yythunkpos125= yy->__thunkpos;
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_EOL(yy)) goto l126;  goto l125;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }  if (!yymatchDot(yy)) goto l125;  goto l124;
  l125:;	  yy->__pos= yypos125; yy->__thunkpos= yythunkpos125;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMENT", yy->__buf+yy->__pos));
  return 1;
  l123:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Syscall(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Syscall"));
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;  if (!yymatchString(yy, "syscall")) goto l129;  if (!yy__(yy)) goto l129;  goto l128;
  l129:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;  if (!yymatchString(yy, "int")) goto l127;  if (!yy__(yy)) goto l127;  if (!yymatchString(yy, "0x80")) goto l127;  if (!yy__(yy)) goto l127;
  }
  l128:;	  yyDo(yy, yy_1_Syscall, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Syscall", yy->__buf+yy->__pos));
  return 1;
  l127:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Syscall", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Branch(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Branch"));  if (!yy_JUMP(yy)) goto l130;  yyDo(yy, yySet, -2, 0);  if (!yymatchChar(yy, '*')) goto l130;  if (!yy_XREG(yy)) goto l130;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_Branch, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Branch", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l130:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Branch", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Load(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Load"));  if (!yy_NAME(yy)) goto l131;  yyDo(yy, yySet, -3, 0);  if (!yy_Addr(yy)) goto l131;  yyDo(yy, yySet, -2, 0);  if (!yy_COMMA(yy)) goto l131;  if (!yy_REG(yy)) goto l131;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_Load, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Load", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l131:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Load", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Store(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Store"));  if (!yy_NAME(yy)) goto l132;  yyDo(yy, yySet, -3, 0);  if (!yy_REG(yy)) goto l132;  yyDo(yy, yySet, -2, 0);  if (!yy_COMMA(yy)) goto l132;  if (!yy_Addr(yy)) goto l132;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_Store, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Store", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Store", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Lea(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Lea"));  if (!yy_LEA(yy)) goto l133;  yyDo(yy, yySet, -3, 0);  if (!yy_AddrNoMod(yy)) goto l133;  yyDo(yy, yySet, -2, 0);  if (!yy_COMMA(yy)) goto l133;  if (!yy_REG(yy)) goto l133;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_Lea, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Lea", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l133:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Lea", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Directive(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Directive"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l134;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '.')) goto l134;
  l135:;	
  {  int yypos136= yy->__pos, yythunkpos136= yy->__thunkpos;
  {  int yypos137= yy->__pos, yythunkpos137= yy->__thunkpos;  if (!yy_EOL(yy)) goto l137;  goto l136;
  l137:;	  yy->__pos= yypos137; yy->__thunkpos= yythunkpos137;
  }  if (!yymatchDot(yy)) goto l136;  goto l135;
  l136:;	  yy->__pos= yypos136; yy->__thunkpos= yythunkpos136;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l134;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l134;  yyDo(yy, yy_1_Directive, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Directive", yy->__buf+yy->__pos));
  return 1;
  l134:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Directive", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Label(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Label"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l138;
#undef yytext
#undef yyleng
  }  if (!yy_ID(yy)) goto l138;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l138;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, ':')) goto l138;  if (!yy__(yy)) goto l138;  yyDo(yy, yy_1_Label, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Label", yy->__buf+yy->__pos));
  return 1;
  l138:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Label", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_INDENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "INDENT"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l139;
#undef yytext
#undef yyleng
  }
  l140:;	
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l141;  goto l140;
  l141:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l139;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_INDENT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "INDENT", yy->__buf+yy->__pos));
  return 1;
  l139:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INDENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Insn(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Insn"));  if (!yy_INDENT(yy)) goto l142;
  {  int yypos143= yy->__pos, yythunkpos143= yy->__thunkpos;  if (!yy_Label(yy)) goto l143;  goto l144;
  l143:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;
  }
  l144:;	
  {  int yypos145= yy->__pos, yythunkpos145= yy->__thunkpos;  if (!yy_Directive(yy)) goto l146;  goto l145;
  l146:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_Lea(yy)) goto l147;  goto l145;
  l147:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_Store(yy)) goto l148;  goto l145;
  l148:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_Load(yy)) goto l149;  goto l145;
  l149:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_Branch(yy)) goto l150;  goto l145;
  l150:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_Syscall(yy)) goto l151;  goto l145;
  l151:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_COMMENT(yy)) goto l152;  goto l145;
  l152:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_Any(yy)) goto l142;
  }
  l145:;	
  {  int yypos153= yy->__pos, yythunkpos153= yy->__thunkpos;  if (!yy_COMMENT(yy)) goto l153;  goto l154;
  l153:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;
  }
  l154:;	  if (!yy_EOL(yy)) goto l142;
  yyprintf((stderr, "  ok   %s @ %s\n", "Insn", yy->__buf+yy->__pos));
  return 1;
  l142:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Insn", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_Insn);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 259 "lfi-amd64.leg"


enum {
    FIXUP_DIST = 8000,
};

static int
dist(int a, int b)
{
    int d = a - b;
    if (d < 0)
        d = -d;
    return d;
}

void
lfigen()
{
    while (yyparse())
        ;

    struct ht labels;
    int icount = 0;
    int r = ht_alloc(&labels, 1024);
    assert(r == 0);

    struct op* op = ops;
    while (op) {
        if (op->label != NULL) {
            ht_put(&labels, op->label, icount);
        }
        icount += op->insn ? 1 : 0;
        op = op->next;
    }

    icount = 0;
    op = ops;
    while (op) {
        if (op->shortbr) {
            bool found;
            int tcount = ht_get(&labels, op->target, &found);
            if (found && op->replace && dist(tcount, icount) > FIXUP_DIST) {
                fprintf(output, "%s", op->replace);
            } else {
                fprintf(output, "%s", op->text);
            }
        } else {
            fprintf(output, "%s", op->text);
        }
        icount += op->insn ? 1 : 0;
        op = op->next;
    }
}

