#!/bin/bash
TOOLCHAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
lfi-compile clang \
    -mllvm --aarch64-enable-compress-jump-tables=false \
    -ffixed-x15 -ffixed-x21 -ffixed-x22 -ffixed-x14 -ffixed-x24 -ffixed-x30 \
    "$@" \
    --sysroot $TOOLCHAIN/sysroot \
    --rtlib=compiler-rt \
    -resource-dir $TOOLCHAIN/compiler-rt \
    -nostdlibinc \
    -isystem $TOOLCHAIN/sysroot/include \
    -isystem /usr/include \
    -target aarch64-linux-musl
