#!/bin/bash
TOOLCHAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
lfi-compile clang \
    -mllvm --aarch64-enable-compress-jump-tables=false \
    -ffixed-x15 -ffixed-x21 -ffixed-x22 -ffixed-x14 -ffixed-x24 -ffixed-x30 \
    "$@" \
    --sysroot $TOOLCHAIN/sysroot \
    --rtlib=compiler-rt \
    -resource-dir $TOOLCHAIN/compiler-rt \
    -stdlib=libc++ \
    -unwindlib=libunwind \
    -nostdlibinc \
    -isystem $TOOLCHAIN/sysroot/include/c++/v1 \
    -isystem $TOOLCHAIN/sysroot/include \
    -isystem /usr/include \
    -fuse-ld=lld \
    -Wno-unused-command-line-argument \
    -lc++ \
    -lunwind \
    -lc++abi \
    -target aarch64-linux-musl
