#!/bin/bash
TOOLCHAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/..
clang++ -fno-integrated-as \
    -mllvm --aarch64-enable-compress-jump-tables=false \
    -ffixed-x18 -ffixed-x21 -ffixed-x22 -ffixed-x23 -ffixed-x24 -ffixed-x30 \
    "$@" \
    -B $TOOLCHAIN/assembler \
    --sysroot $TOOLCHAIN/sysroot \
    --rtlib=compiler-rt \
    -resource-dir $TOOLCHAIN/compiler-rt \
    -stdlib=libc++ \
    -unwindlib=libunwind \
    -nostdlibinc \
    -isystem $TOOLCHAIN/sysroot/include/c++/v1 \
    -isystem $TOOLCHAIN/sysroot/include \
    -isystem /usr/include \
    -lc++ \
    -lunwind \
    -lc++abi \
    -target aarch64-linux-musl
