#!/bin/bash
TOOLCHAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/..
lfi-compile clang \
    -mllvm --aarch64-enable-compress-jump-tables=false \
    -ffixed-x18 -ffixed-x21 -ffixed-x22 -ffixed-x25 -ffixed-x30 \
    "$@" \
    --sysroot $TOOLCHAIN/sysroot \
    --rtlib=compiler-rt \
    -resource-dir $TOOLCHAIN/compiler-rt \
    -nostdlibinc \
    -isystem $TOOLCHAIN/sysroot/include \
    -isystem /usr/include \
    -isystem /usr/include/aarch64-linux-gnu \
    -fuse-ld=lld \
    -Wno-unused-command-line-argument \
    -static-pie \
    -target aarch64-linux-musl
