#!/bin/bash
lfi-compile clang++ \
    -mllvm --aarch64-enable-compress-jump-tables=false \
    -ffixed-x18 -ffixed-x21 -ffixed-x22 -ffixed-x25 -ffixed-x30 \
    "$@" \
    -fuse-ld=lld \
    -fPIC \
    -Wno-unused-command-line-argument
