#!/bin/sh
TOOLCHAIN=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/..
export LFIFLAGS="{{ .LfiFlags }}"
export LFIARCH="{{ .Arch }}"
lfi-compile {{ .Compiler }} \
    {{ .LegFlags }} \
    "$@" \
    --sysroot $TOOLCHAIN/sysroot \
    --rtlib=compiler-rt \
    -resource-dir $TOOLCHAIN/compiler-rt \
    -nostdlibinc \
    -isystem $TOOLCHAIN/sysroot/include \
    -isystem /usr/include \
    -isystem /usr/include/x86_64-linux-gnu \
    -fuse-ld=lld \
    -Wno-unused-command-line-argument \
    {{ .ExtraFlags }}
