#!/bin/sh
TOOLCHAIN=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/..
export LFIFLAGS="{{ .LfiFlags }}"
export LFIARCH="{{ .Arch }}"
export POSTLINKFLAGS="{{ .PostlinkFlags }}"
lfi-compile {{ .Compiler }} \
    {{ .LegFlags }} \
    "$@" \
    --sysroot $TOOLCHAIN/sysroot \
    --rtlib=compiler-rt \
    -resource-dir $TOOLCHAIN/compiler-rt \
    -stdlib=libc++ \
    -unwindlib=libunwind \
    -nostdlibinc \
    -isystem $TOOLCHAIN/sysroot/include/c++/v1 \
    -isystem $TOOLCHAIN/sysroot/include \
    -isystem /usr/include \
    -isystem /usr/include/{{ .GnuArch }}-linux-gnu \
    -fuse-ld=lld \
    -Wno-unused-command-line-argument \
    -lc++ \
    -lunwind \
    -lc++abi \
    {{ .ExtraFlags }}
