#!/bin/sh
TOOLCHAIN=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/..
export LFIFLAGS="$LFIFLAGS {{ .LfiFlags }}"
lfi-compile {{ .Compiler }} \
    $(lfi-leg --flags={{ .Toolchain }}) \
    "$@" \
    -fuse-ld=lld \
    -Wno-unused-command-line-argument \
    {{ .ExtraFlags }}
