#!/bin/sh
TOOLCHAIN=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/..
export LFIFLAGS="{{ .LfiFlags }}"
export LFIARCH="{{ .Arch }}"
lfi-compile {{ .Compiler }} \
    {{ .LegFlags }} \
    "$@" \
    -fuse-ld=lld \
    -Wno-unused-command-line-argument \
    {{ .ExtraFlags }}
