use bad64::Op;

use crate::autogen::is_allowed_autogen;

// Some instruction type definitions. Partially auto-verified using armgen.

pub fn nomodify(op: Op) -> bool {
    match op {
        // arithmetic
        Op::NOP => true,
        Op::CMP => true,
        Op::CMN => true,
        Op::PRFM => true,
        Op::PRFUM => true,
        // branches
        Op::RET => true,
        Op::BLR => true,
        Op::BR => true,
        Op::BL => true,
        Op::BTI => true,
        Op::B_AL => true,
        Op::B_CC => true,
        Op::B_CS => true,
        Op::B_EQ => true,
        Op::B_GE => true,
        Op::B_GT => true,
        Op::B_HI => true,
        Op::B_LE => true,
        Op::B_LS => true,
        Op::B_LT => true,
        Op::B_MI => true,
        Op::B_NE => true,
        Op::B_NV => true,
        Op::B_PL => true,
        Op::B_VC => true,
        Op::B_VS => true,
        Op::B => true,
        Op::TBZ => true,
        Op::TBNZ => true,
        Op::CBZ => true,
        Op::CBNZ => true,
        // stores
        Op::ST1 => true,
        Op::ST2 => true,
        Op::ST3 => true,
        Op::ST4 => true,
        Op::STLR => true,
        Op::STLRB => true,
        Op::STLRH => true,
        Op::STNP => true,
        Op::STP => true,
        Op::STR => true,
        Op::STRB => true,
        Op::STRH => true,
        Op::STTR => true,
        Op::STTRB => true,
        Op::STTRH => true,
        Op::STUR => true,
        Op::STURB => true,
        Op::STURH => true,

        _ => false,
    }
}

pub fn is_multimod(op: Op) -> bool {
    match op {
        Op::LDP => true,
        Op::LDPSW => true,
        Op::LDNP => true,
        Op::LDXP => true,
        Op::LDAXP => true,
        Op::CAS => true,
        Op::CASA => true,
        Op::CASAL => true,
        Op::CASL => true,
        Op::CASB => true,
        Op::CASLB => true,
        Op::CASAB => true,
        Op::CASALB => true,
        Op::CASALH => true,
        Op::CASH => true,
        Op::CASLH => true,
        Op::CASAH => true,
        Op::CASPA => true,
        Op::CASPAL => true,
        Op::CASPL => true,
        Op::CASP => true,
        Op::SWP => true,
        Op::SWPA => true,
        Op::SWPAL => true,
        Op::SWPL => true,
        Op::SWPAB => true,
        Op::SWPALB => true,
        Op::SWPB => true,
        Op::SWPLB => true,
        Op::SWPAH => true,
        Op::SWPALH => true,
        Op::SWPH => true,
        Op::SWPLH => true,
        Op::LDADD => true,
        Op::LDADDA => true,
        Op::LDADDAL => true,
        Op::LDADDL => true,
        Op::LDADDB => true,
        Op::LDADDLB => true,
        Op::LDADDAB => true,
        Op::LDADDALB => true,
        Op::LDADDAH => true,
        Op::LDADDALH => true,
        Op::LDADDH => true,
        Op::LDADDLH => true,
        Op::LDCLR => true,
        Op::LDCLRA => true,
        Op::LDCLRAL => true,
        Op::LDCLRL => true,
        Op::LDCLRAB => true,
        Op::LDCLRALB => true,
        Op::LDCLRB => true,
        Op::LDCLRLB => true,
        Op::LDCLRAH => true,
        Op::LDCLRALH => true,
        Op::LDCLRH => true,
        Op::LDCLRLH => true,
        Op::LDEOR => true,
        Op::LDEORA => true,
        Op::LDEORAL => true,
        Op::LDEORL => true,
        Op::LDEORAB => true,
        Op::LDEORALB => true,
        Op::LDEORB => true,
        Op::LDEORLB => true,
        Op::LDEORAH => true,
        Op::LDEORALH => true,
        Op::LDEORH => true,
        Op::LDEORLH => true,
        Op::LDSET => true,
        Op::LDSETA => true,
        Op::LDSETAL => true,
        Op::LDSETL => true,
        Op::LDSETAB => true,
        Op::LDSETALB => true,
        Op::LDSETB => true,
        Op::LDSETLB => true,
        Op::LDSETAH => true,
        Op::LDSETALH => true,
        Op::LDSETH => true,
        Op::LDSETLH => true,
        Op::LDSMAX => true,
        Op::LDSMAXA => true,
        Op::LDSMAXAL => true,
        Op::LDSMAXL => true,
        Op::LDSMAXAB => true,
        Op::LDSMAXALB => true,
        Op::LDSMAXB => true,
        Op::LDSMAXLB => true,
        Op::LDSMAXAH => true,
        Op::LDSMAXALH => true,
        Op::LDSMAXH => true,
        Op::LDSMAXLH => true,
        Op::LDSMIN => true,
        Op::LDSMINA => true,
        Op::LDSMINAL => true,
        Op::LDSMINL => true,
        Op::LDSMINAB => true,
        Op::LDSMINALB => true,
        Op::LDSMINB => true,
        Op::LDSMINLB => true,
        Op::LDSMINAH => true,
        Op::LDSMINALH => true,
        Op::LDSMINH => true,
        Op::LDSMINLH => true,
        Op::LDUMAX => true,
        Op::LDUMAXA => true,
        Op::LDUMAXAL => true,
        Op::LDUMAXL => true,
        Op::LDUMAXAB => true,
        Op::LDUMAXALB => true,
        Op::LDUMAXB => true,
        Op::LDUMAXLB => true,
        Op::LDUMAXALH => true,
        Op::LDUMAXH => true,
        Op::LDUMAXLH => true,
        Op::LDUMAXAH => true,
        Op::LDUMINA => true,
        Op::LDUMINAL => true,
        Op::LDUMINL => true,
        Op::LDUMIN => true,
        Op::LDUMINAB => true,
        Op::LDUMINALB => true,
        Op::LDUMINB => true,
        Op::LDUMINLB => true,
        Op::LDUMINAH => true,
        Op::LDUMINALH => true,
        Op::LDUMINH => true,
        Op::LDUMINLH => true,
        _ => false,
    }
}

// Extra instructions that don't get generated by armgen (mostly aliases and specifically allowed
// system instructions).
pub fn is_allowed(op: Op) -> bool {
    match op {
        Op::NOP => true,
        Op::MSR | Op::MRS => true,
        Op::DMB => true,
        Op::BFC => true,
        Op::UXTL2 | Op::SXTL2 => true,
        Op::UADDW2 | Op::UADDL2 | Op::SSUBW2 | Op::USUBL2 | Op::UMULL2 | Op::UMLAL2 | Op::RSHRN2 | Op::SADDW2 | Op::USUBW2 | Op::SADDL2 | Op::SSUBL2 => true,
        Op::SMLAL2 | Op::SHLL2 | Op::SMULL2 | Op::UABAL2 | Op::USHLL2 | Op::UABDL2 => true,
        Op::MSB | Op::MAD | Op::SADDV | Op::UADDV | Op::SUBR | Op::ASRD | Op::MOVPRFX | Op::ASRR | Op::LSRR | Op::LSLR | Op::ORV | Op::EORV | Op::ANDV | Op::CNOT | Op::EOR3 | Op::INDEX => true,
        Op::FMLA | Op::FMLS => true,
        Op::FABD => true,
        Op::FADDP => true,
        Op::FCVTN2 | Op::FCVTL2 => true,
        Op::FCMGE | Op::FCMGT | Op::FCMLE | Op::FCMEQ | Op::FCMLT => true,
        Op::BRK => true,
        Op::XTN2 => true,
        Op::SHRN2 => true,
        Op::AUTIA1716 | Op::AUTIB1716 => true,
        Op::STLR => true,
        Op::BTI => true,
        Op::XPACLRI | Op::XPACI | Op::XPACD => true,
        Op::CNTD | Op::CNTB | Op::CNTH | Op::CNTP | Op::CNTW => true,
        _ => is_allowed_autogen(op),
    }
}
