use bad64::Reg;

pub fn lo_reg(reg: Reg) -> bool {
    match reg {
        Reg::W0 => true,
        Reg::W1 => true,
        Reg::W2 => true,
        Reg::W3 => true,
        Reg::W4 => true,
        Reg::W5 => true,
        Reg::W6 => true,
        Reg::W7 => true,
        Reg::W8 => true,
        Reg::W9 => true,
        Reg::W10 => true,
        Reg::W11 => true,
        Reg::W12 => true,
        Reg::W13 => true,
        Reg::W14 => true,
        Reg::W15 => true,
        Reg::W16 => true,
        Reg::W17 => true,
        Reg::W18 => true,
        Reg::W19 => true,
        Reg::W20 => true,
        Reg::W21 => true,
        Reg::W22 => true,
        Reg::W23 => true,
        Reg::W24 => true,
        Reg::W25 => true,
        Reg::W26 => true,
        Reg::W27 => true,
        Reg::W28 => true,
        Reg::W29 => true,
        Reg::W30 => true,
        Reg::WZR => true,
        Reg::WSP => true,
        _ => false,
    }
}

pub fn lo(reg: Reg) -> Reg {
    match reg {
        Reg::X0 => Reg::W0,
        Reg::X1 => Reg::W1,
        Reg::X2 => Reg::W2,
        Reg::X3 => Reg::W3,
        Reg::X4 => Reg::W4,
        Reg::X5 => Reg::W5,
        Reg::X6 => Reg::W6,
        Reg::X7 => Reg::W7,
        Reg::X8 => Reg::W8,
        Reg::X9 => Reg::W9,
        Reg::X10 => Reg::W10,
        Reg::X11 => Reg::W11,
        Reg::X12 => Reg::W12,
        Reg::X13 => Reg::W13,
        Reg::X14 => Reg::W14,
        Reg::X15 => Reg::W15,
        Reg::X16 => Reg::W16,
        Reg::X17 => Reg::W17,
        Reg::X18 => Reg::W18,
        Reg::X19 => Reg::W19,
        Reg::X20 => Reg::W20,
        Reg::X21 => Reg::W21,
        Reg::X22 => Reg::W22,
        Reg::X23 => Reg::W23,
        Reg::X24 => Reg::W24,
        Reg::X25 => Reg::W25,
        Reg::X26 => Reg::W26,
        Reg::X27 => Reg::W27,
        Reg::X28 => Reg::W28,
        Reg::X29 => Reg::W29,
        Reg::X30 => Reg::W30,
        Reg::XZR => Reg::WZR,
        Reg::SP => Reg::WSP,
        _ => reg,
    }
}
